<?php

namespace Smath\ProductoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * proveedorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class proveedorRepository extends EntityRepository
{
}
