<?php

namespace Smath\ProductoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * tipoproveedorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tipoproveedorRepository extends EntityRepository
{
}
